[package]
name = "xtab"
version = "0.0.1"
edition = "2021"
homepage = "https://github.com/sharkLoc/xtab"
description = "xtab: CSV command line utilities"
keywords = ["csv"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.5", features = ["derive"] }
csv = "1.2.2"
env_logger = "0.10.0"
flate2 = "1.0.27"
log = "0.4.20"
